//
// Copyright 2026 hesphoros
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//
// 日本語 localization
// Save as UTF-8 with BOM (required for MSVC to parse non-ASCII correctly).

const utf8_t *_localization_string_array_ja[LOCALIZATION_ID_COUNT] = 
{
	// Application name
	"日本語", // LOCALIZATION_ID_LANGUAGE

	// Language names (for the language selection menu)
	"English (US)", // LOCALIZATION_ID_LANGUAGE_ENGLISH
	"简体中文", // LOCALIZATION_ID_LANGUAGE_CHINESE_SIMPLIFIED
	"日本語", // LOCALIZATION_ID_LANGUAGE_JAPANESE
	"한국어", // LOCALIZATION_ID_LANGUAGE_KOREAN
	"Français", // LOCALIZATION_ID_LANGUAGE_FRENCH
	"Deutsch", // LOCALIZATION_ID_LANGUAGE_GERMAN
	"Español", // LOCALIZATION_ID_LANGUAGE_SPANISH
	"Português", // LOCALIZATION_ID_LANGUAGE_PORTUGUESE
	"Italiano", // LOCALIZATION_ID_LANGUAGE_ITALIAN
	"العربية", // LOCALIZATION_ID_LANGUAGE_ARABIC
	
	// Application name
	"void Image Viewer", // LOCALIZATION_ID_APP_NAME

	// File menu
	"ファイル(&F)", // LOCALIZATION_ID_FILE,
	"ファイルを開く(&O)...", // LOCALIZATION_ID_OPEN_FILE,
	"フォルダーを開く(&F)...", // LOCALIZATION_ID_OPEN_FOLDER,
	"Everything 検索を開く(&S)...", // LOCALIZATION_ID_OPEN_EVERYTHING_SEARCH,
	"ファイルを追加(&A)...", // LOCALIZATION_ID_ADD_FILE,
	"フォルダーを追加...", // LOCALIZATION_ID_ADD_FOLDER,
	"Everything 検索を追加...", // LOCALIZATION_ID_ADD_EVERYTHING_SEARCH,
	"ファイルの場所を開く(&L)...", // LOCALIZATION_ID_OPEN_FILE_LOCATION,
	"編集(&E)...", // LOCALIZATION_ID_EDIT,
	"プレビュー(&V)...", // LOCALIZATION_ID_PREVIEW,
	"印刷(&P)...", // LOCALIZATION_ID_PRINT,
	"デスクトップの壁紙に設定(&D)", // LOCALIZATION_ID_SET_DESKTOP_WALLPAPER,
	"閉じる(&C)", // LOCALIZATION_ID_CLOSE,
	"削除(&D)", // LOCALIZATION_ID_DELETE,
	"削除(ごみ箱)", // LOCALIZATION_ID_DELETE_RECYCLE,
	"削除(完全)", // LOCALIZATION_ID_DELETE_PERMANENTLY,
	"名前を変更(&M)", // LOCALIZATION_ID_RENAME,
	"プロパティ(&R)", // LOCALIZATION_ID_PROPERTIES,
	"終了(&X)", // LOCALIZATION_ID_EXIT,
	
	// Edit menu
	"編集(&E)", // LOCALIZATION_ID_EDIT_MENU,
	"切り取り(&T)", // LOCALIZATION_ID_CUT,
	"コピー(&C)", // LOCALIZATION_ID_COPY,
	"ファイル名をコピー", // LOCALIZATION_ID_COPY_FILENAME,
	"画像をコピー(&Y)", // LOCALIZATION_ID_COPY_IMAGE,
	"貼り付け(&P)", // LOCALIZATION_ID_PASTE,
	"右回転(&K)", // LOCALIZATION_ID_ROTATE_CLOCKWISE,
	"左回転(&N)", // LOCALIZATION_ID_ROTATE_COUNTERCLOCKWISE,
	"フォルダーへコピー(&F)...", // LOCALIZATION_ID_COPY_TO,
	"フォルダーへ移動(&V)...", // LOCALIZATION_ID_MOVE_TO,
	
	// View menu
	"表示(&V)", // LOCALIZATION_ID_VIEW,
	"キャプション", // LOCALIZATION_ID_CAPTION,
	"フレーム", // LOCALIZATION_ID_FRAME,
	"メニュー(&M)", // LOCALIZATION_ID_MENU,
	"ステータスバー(&B)", // LOCALIZATION_ID_STATUS_BAR,
	"コントロール(&C)", // LOCALIZATION_ID_CONTROLS,
	"プリセット(&P)", // LOCALIZATION_ID_PRESET,
	"最小(&M)", // LOCALIZATION_ID_MINIMAL,
	"コンパクト(&C)", // LOCALIZATION_ID_COMPACT,
	"標準(&N)", // LOCALIZATION_ID_NORMAL,
	"全画面(&F)", // LOCALIZATION_ID_FULLSCREEN,
	"スライドショー(&S)", // LOCALIZATION_ID_SLIDESHOW,
	"ウィンドウサイズ(&W)", // LOCALIZATION_ID_VIEW_WINDOW_SIZE,
	"50%", // LOCALIZATION_ID_VIEW_WINDOW_SIZE_50_PERCENT,
	"100%", // LOCALIZATION_ID_VIEW_WINDOW_SIZE_100_PERCENT,
	"200%", // LOCALIZATION_ID_VIEW_WINDOW_SIZE_200_PERCENT,
	"自動フィット(&A)", // LOCALIZATION_ID_VIEW_WINDOW_SIZE_AUTO_FIT,
	"更新(&R)", // LOCALIZATION_ID_REFRESH,
	"縮小を許可(&A)", // LOCALIZATION_ID_ALLOW_SHRINKING,
	"縦横比を維持(&K)", // LOCALIZATION_ID_KEEP_ASPECT_RATIO,
	"ウィンドウに合わせる(&F)", // LOCALIZATION_ID_FILL_WINDOW,
	"1:1", // LOCALIZATION_ID_ONE_TO_ONE,
	"最適表示(&B)", // LOCALIZATION_ID_BEST_FIT,
	"パンとスキャン(&N)", // LOCALIZATION_ID_PAN_SCAN,
	"サイズを拡大(&I)", // LOCALIZATION_ID_INCREASE_SIZE,
	"サイズを縮小(&D)", // LOCALIZATION_ID_DECREASE_SIZE,
	"幅を拡大(&N)", // LOCALIZATION_ID_INCREASE_WIDTH,
	"幅を縮小(&E)", // LOCALIZATION_ID_DECREASE_WIDTH,
	"高さを拡大(&C)", // LOCALIZATION_ID_INCREASE_HEIGHT,
	"高さを縮小(&R)", // LOCALIZATION_ID_DECREASE_HEIGHT,
	"ズーム(&Z)", // LOCALIZATION_ID_ZOOM,
	"ズームイン(&I)", // LOCALIZATION_ID_ZOOM_IN,
	"ズームアウト(&O)", // LOCALIZATION_ID_ZOOM_OUT,
	"リセット(&R)", // LOCALIZATION_ID_RESET,
	"上へ移動(&U)", // LOCALIZATION_ID_MOVE_UP,
	"下へ移動(&D)", // LOCALIZATION_ID_MOVE_DOWN,
	"左へ移動(&L)", // LOCALIZATION_ID_MOVE_LEFT,
	"右へ移動(&R)", // LOCALIZATION_ID_MOVE_RIGHT,
	"左上へ移動", // LOCALIZATION_ID_MOVE_UP_LEFT,
	"右上へ移動", // LOCALIZATION_ID_MOVE_UP_RIGHT,
	"左下へ移動", // LOCALIZATION_ID_MOVE_DOWN_LEFT,
	"右下へ移動", // LOCALIZATION_ID_MOVE_DOWN_RIGHT,
	"中央へ移動(&T)", // LOCALIZATION_ID_MOVE_CENTER,
	"リセット(&S)", // LOCALIZATION_ID_PANSCAN_RESET,
	"常に手前(&T)", // LOCALIZATION_ID_ON_TOP,
	"常に(&A)", // LOCALIZATION_ID_ALWAYS,
	"スライドショーまたはアニメーション再生中(&W)", // LOCALIZATION_ID_WHILE_PLAYING_OR_ANIMATING,
	"しない(&N)", // LOCALIZATION_ID_NEVER,
	"オプション(&O)...", // LOCALIZATION_ID_OPTIONS,
	"トランジション(&T)", // LOCALIZATION_ID_TRANSITION,
	"なし(&N)", // LOCALIZATION_ID_TRANSITION_NONE,
	"フェード(&F)", // LOCALIZATION_ID_TRANSITION_FADE,
	"時間...", // LOCALIZATION_ID_TRANSITION_DURATION,
	
	// Slideshow menu
	"スライドショー(&S)", // LOCALIZATION_ID_SLIDESHOW_MENU,
	"再生/一時停止(&P)", // LOCALIZATION_ID_PLAY_PAUSE,
	"速度(&R)", // LOCALIZATION_ID_RATE,
	"速度を下げる(&D)", // LOCALIZATION_ID_DECREASE_RATE,
	"速度を上げる(&I)", // LOCALIZATION_ID_INCREASE_RATE,
	"250 ミリ秒", // LOCALIZATION_ID_RATE_250_MILLISECONDS,
	"500 ミリ秒", // LOCALIZATION_ID_RATE_500_MILLISECONDS,
	"1 秒(&1)", // LOCALIZATION_ID_RATE_1_SECOND,
	"2 秒(&2)", // LOCALIZATION_ID_RATE_2_SECONDS,
	"3 秒(&3)", // LOCALIZATION_ID_RATE_3_SECONDS,
	"4 秒(&4)", // LOCALIZATION_ID_RATE_4_SECONDS,
	"5 秒(&5)", // LOCALIZATION_ID_RATE_5_SECONDS,
	"6 秒(&6)", // LOCALIZATION_ID_RATE_6_SECONDS,
	"7 秒(&7)", // LOCALIZATION_ID_RATE_7_SECONDS,
	"8 秒(&8)", // LOCALIZATION_ID_RATE_8_SECONDS,
	"9 秒(&9)", // LOCALIZATION_ID_RATE_9_SECONDS,
	"10 秒(&0)", // LOCALIZATION_ID_RATE_10_SECONDS,
	"20 秒", // LOCALIZATION_ID_RATE_20_SECONDS,
	"30 秒", // LOCALIZATION_ID_RATE_30_SECONDS,
	"40 秒", // LOCALIZATION_ID_RATE_40_SECONDS,
	"50 秒", // LOCALIZATION_ID_RATE_50_SECONDS,
	"1 分",	// LOCALIZATION_ID_RATE_1_MINUTE,
	"カスタム...", // LOCALIZATION_ID_CUSTOM,
	"アニメーション時間(&D)", // LOCALIZATION_ID_RATE_ANIMATION_DURATION,
	
	// Animation menu
	"アニメーション(&A)", // LOCALIZATION_ID_ANIMATION,
	"再生/一時停止(&P)", // LOCALIZATION_ID_ANIMATION_PLAY_PAUSE,
	"前方へジャンプ(&F)", // LOCALIZATION_ID_ANIMATION_JUMP_FORWARD,
	"後方へジャンプ(&B)", // LOCALIZATION_ID_ANIMATION_JUMP_BACKWARD,
	"短く前方へジャンプ(&F)", // LOCALIZATION_ID_ANIMATION_SHORT_JUMP_FORWARD,
	"短く後方へジャンプ(&B)", // LOCALIZATION_ID_ANIMATION_SHORT_JUMP_BACKWARD,
	"長く前方へジャンプ(&F)", // LOCALIZATION_ID_ANIMATION_LONG_JUMP_FORWARD,
	"長く後方へジャンプ(&B)", // LOCALIZATION_ID_ANIMATION_LONG_JUMP_BACKWARD,
	"フレーム送り(&R)", // LOCALIZATION_ID_ANIMATION_FRAME_STEP,
	"前のフレーム(&V)", // LOCALIZATION_ID_ANIMATION_PREVIOUS_FRAME,
	"最初のフレーム(&F)", // LOCALIZATION_ID_ANIMATION_FIRST_FRAME,
	"最後のフレーム(&L)", // LOCALIZATION_ID_ANIMATION_LAST_FRAME,
	"速度を下げる(&D)", // LOCALIZATION_ID_ANIMATION_DECREASE_RATE,
	"速度を上げる(&I)", // LOCALIZATION_ID_ANIMATION_INCREASE_RATE,
	"速度をリセット(&R)", // LOCALIZATION_ID_ANIMATION_RESET_RATE,
	
	// Navigate menu
	"ナビゲート(&N)", // LOCALIZATION_ID_NAVIGATE,
	"次へ(&N)", // LOCALIZATION_ID_NEXT,
	"前へ(&R)", // LOCALIZATION_ID_PREVIOUS,
	"ホーム(&H)", // LOCALIZATION_ID_HOME,
	"最後(&E)", // LOCALIZATION_ID_END,
	"並べ替え(&S)", // LOCALIZATION_ID_SORT,
	"名前(&N)", // LOCALIZATION_ID_SORT_NAME,
	"フルパス(&P)", // LOCALIZATION_ID_SORT_FULL_PATH,
	"サイズ(&S)", // LOCALIZATION_ID_SORT_SIZE,
	"更新日時(&M)", // LOCALIZATION_ID_SORT_DATE_MODIFIED,
	"作成日時(&C)", // LOCALIZATION_ID_SORT_DATE_CREATED,
	"昇順(&A)", // LOCALIZATION_ID_SORT_ASCENDING,
	"降順(&D)", // LOCALIZATION_ID_SORT_DESCENDING,
	"シャッフル", // LOCALIZATION_ID_SHUFFLE,
	"ジャンプ(&J)...", // LOCALIZATION_ID_JUMP_TO,
	
	// Help menu
	"ヘルプ(&H)", // LOCALIZATION_ID_HELP,
	"ヘルプ(&H)", // LOCALIZATION_ID_HELP_MENU,
	"コマンドラインオプション(&C)", // LOCALIZATION_ID_COMMAND_LINE_OPTIONS,
	"ホームページ(&P)", // LOCALIZATION_ID_HOME_PAGE,
	"寄付(&D)", // LOCALIZATION_ID_DONATE,
	"バージョン情報(&A)", // LOCALIZATION_ID_ABOUT,
	"https://www.voidtools.com/support/voidimageviewer/", // LOCALIZATION_ID_HELP_SUPPORT_URL,
	"https://www.voidtools.com/donate/", // LOCALIZATION_ID_HELP_DONATE_URL,
	"https://www.voidtools.com/", // LOCALIZATION_ID_HELP_WEBSITE_URL,

	// Toolbar
	"前の画像", // LOCALIZATION_ID_TOOLBAR_PREVIOUS_IMAGE_BUTTON,
	"次の画像", // LOCALIZATION_ID_TOOLBAR_NEXT_IMAGE_BUTTON,
	"スライドショーを再生", // LOCALIZATION_ID_TOOLBAR_PLAY_SLIDESHOW_BUTTON,
	"スライドショーを一時停止", // LOCALIZATION_ID_TOOLBAR_PAUSE_SLIDESHOW_BUTTON,
	"最適表示", // LOCALIZATION_ID_TOOLBAR_BEST_FIT_BUTTON,
	"実寸表示", // LOCALIZATION_ID_TOOLBAR_ACTUAL_SIZE_BUTTON,

	// Status bar
	"PRELOAD", // LOCALIZATION_ID_STATUS_BAR_PRELOAD,
	"読み込み中...", // LOCALIZATION_ID_STATUS_BAR_LOADING,
	"ファイルが見つかりません。", // LOCALIZATION_ID_STATUS_BAR_FILE_NOT_FOUND,
	"画像の読み込みに失敗しました。", // LOCALIZATION_ID_STATUS_BAR_FAILED_TO_LOAD_IMAGE,
	"スライドショー再生中", // LOCALIZATION_ID_STATUS_BAR_SLIDESHOW_PLAYING,
	"位置 %0.3f %0.3f、ズーム %0.3f %0.3f、縦横比 %0.3f", // LOCALIZATION_ID_STATUS_BAR_POS_ZOOM_FORMAT,
	"アニメーション速度 %0.3f", // LOCALIZATION_ID_STATUS_BAR_ANIMATION_RATE_FORMAT,
	"スライドショー速度 %d %s", // LOCALIZATION_ID_STATUS_BAR_SLIDESHOW_RATE_FORMAT,
	"スライドショー速度: アニメーション時間", // LOCALIZATION_ID_STATUS_BAR_ANIMATION_DURATION,
	"分", // LOCALIZATION_ID_STATUS_BAR_MINUTES,
	"秒", // LOCALIZATION_ID_STATUS_BAR_SECONDS,
	"ミリ秒", // LOCALIZATION_ID_STATUS_BAR_MILLISECONDS,

	// Dialog strings
	"オプション - void Image Viewer", // LOCALIZATION_ID_OPTIONS_CAPTION,
	"全般", // LOCALIZATION_ID_OPTIONS_GENERAL_DIALOG,
	"表示", // LOCALIZATION_ID_OPTIONS_VIEW_DIALOG,
	"コントロール", // LOCALIZATION_ID_OPTIONS_CONTROLS_DIALOG,
	"OK", // LOCALIZATION_ID_OK_BUTTON,
	"キャンセル", // LOCALIZATION_ID_CANCEL_BUTTON,
	"設定を %APPDATA%\\voidImageViewer に保存(&S)", // LOCALIZATION_ID_STORE_SETTINGS_APPDATA,
	"複数のインスタンスを許可(&I)", // LOCALIZATION_ID_ALLOW_MULTIPLE_INSTANCES,
	"スタートメニューのショートカット(&M)", // LOCALIZATION_ID_STARTMENU_SHORTCUTS,
	"関連付け", // LOCALIZATION_ID_ASSOCIATIONS,
	"すべて選択(&A)", // LOCALIZATION_ID_CHECK_ALL,
	"すべて解除(&N)", // LOCALIZATION_ID_CHECK_NONE,
	"縮小ブリットモード:(&S)", // LOCALIZATION_ID_SHRINK_BLIT_MODE_STATIC,
	"拡大ブリットモード:(&M)", // LOCALIZATION_ID_MAGNIFY_BLIT_MODE,
	"最近傍", // LOCALIZATION_ID_BLIT_MODE_NEAREST_COMBOBOXITEM,
	"線形", // LOCALIZATION_ID_BLIT_MODE_LINEAR_COMBOBOXITEM,
	"ウィンドウ自動サイズ:(&Z)", // LOCALIZATION_ID_OPTIONS_VIEW_AUTO_SIZE_WINDOW_STATIC,
	"50%", // LOCALIZATION_ID_OPTIONS_VIEW_AUTO_SIZE_WINDOW_50_PERCENT_COMBOBOXITEM,
	"100%", // LOCALIZATION_ID_OPTIONS_VIEW_AUTO_SIZE_WINDOW_100_PERCENT_COMBOBOXITEM,
	"200%", // LOCALIZATION_ID_OPTIONS_VIEW_AUTO_SIZE_WINDOW_200_PERCENT_COMBOBOXITEM,
	"自動フィット", // LOCALIZATION_ID_OPTIONS_VIEW_AUTO_SIZE_WINDOW_AUTO_FIT_COMBOBOXITEM,
	"スライドショーでアニメーションを最低1回再生(&P)", // LOCALIZATION_ID_PLAY_ANIMATIONS_ONCE_STATIC,
	"次の画像をプリロード(&N)", // LOCALIZATION_ID_PRELOAD_NEXT_IMAGE_STATIC,
	"最後の画像をキャッシュ(&L)", // LOCALIZATION_ID_CACHE_LAST_IMAGE_STATIC,
	"ウィンドウ背景色:(&W)", // LOCALIZATION_ID_WINDOWED_BACKGROUND_COLOR_STATIC,
	"全画面背景色:(&F)", // LOCALIZATION_ID_FULLSCREEN_BACKGROUND_COLOR_STATIC,
	"左クリックアクション:(&L)", // LOCALIZATION_ID_LEFT_CLICK_ACTION_STATIC,
	"右クリックアクション:(&R)", // LOCALIZATION_ID_RIGHT_CLICK_ACTION_STATIC,
	"マウスホイールアクション:(&M)", // LOCALIZATION_ID_MOUSE_WHEEL_ACTION_STATIC,
	"コマンド:(&C)", // LOCALIZATION_ID_COMMANDS_STATIC,
	"選択したコマンドの設定", // LOCALIZATION_ID_SETTINGS_FOR_SELECTED_COMMAND,
	"追加(&A)...", // LOCALIZATION_ID_ADD_KEY_BUTTON,
	"編集(&E)...", // LOCALIZATION_ID_EDIT_KEY_BUTTON,
	"削除(&V)", // LOCALIZATION_ID_REMOVE_KEY_BUTTON,
	"キーボードショートカットを追加", // LOCALIZATION_ID_ADD_KEYBOARD_SHORTCUT_CAPTION,
	"キーボードショートカットを編集", // LOCALIZATION_ID_EDIT_KEYBOARD_SHORTCUT_CAPTION,
	"ショートカットキー:(&K)", // LOCALIZATION_ID_SHORTCUT_KEY,
	"ショートカットキーが使用中:", // LOCALIZATION_ID_SHORTCUT_KEY_CURRENTLY_USED_BY,
	"カスタム速度を設定", // LOCALIZATION_ID_SET_CUSTOM_RATE_CAPTION,
	"カスタム速度:(&C)", // LOCALIZATION_ID_CUSTOM_RATE_STATIC,
	"分", // LOCALIZATION_ID_CUSTOM_RATE_MINUTES,
	"秒", // LOCALIZATION_ID_CUSTOM_RATE_SECONDS,
	"ミリ秒", // LOCALIZATION_ID_CUSTOM_RATE_MILLISECONDS,
	"void Image Viewer について", // LOCALIZATION_ID_ABOUT_CAPTION,
	"名前を変更", // LOCALIZATION_ID_RENAME_CAPTION,
	"ジャンプ", // LOCALIZATION_ID_JUMP_TO_TITLE,
	"Copyright © %d voidtools", // LOCALIZATION_ID_ABOUT_COPYRIGHT_FORMAT,
	"support@voidtools.com", // LOCALIZATION_ID_ABOUT_EMAIL,
	"www.voidtools.com", // LOCALIZATION_ID_ABOUT_WEBSITE,
	"画像を開く", // LOCALIZATION_ID_OPEN_IMAGE_CAPTION,
	"すべての画像ファイル", // LOCALIZATION_ID_OPEN_ALL_IMAGE_FILES,
	"すべてのファイル", // LOCALIZATION_ID_OPEN_ALL_FILES,
	"スクロール", // LOCALIZATION_ID_OPTIONS_ACTION_SCROLL_COMBOBOXITEM,
	"スライドショー再生/一時停止", // LOCALIZATION_ID_OPTIONS_ACTION_PLAY_PAUSE_SLIDESHOW_COMBOBOXITEM,
	"アニメーション再生/一時停止", // LOCALIZATION_ID_OPTIONS_ACTION_PLAY_PAUSE_ANIMATION_COMBOBOXITEM,
	"ズームイン", // LOCALIZATION_ID_OPTIONS_ACTION_ZOOM_IN_COMBOBOXITEM,
	"次の画像", // LOCALIZATION_ID_OPTIONS_ACTION_NEXT_IMAGE_COMBOBOXITEM,
	"1:1 スクロール", // LOCALIZATION_ID_OPTIONS_ACTION_ONE_TO_ONE_SCROLL_COMBOBOXITEM,
	"スクロール/ウィンドウ移動", // LOCALIZATION_ID_OPTIONS_ACTION_SCROLL_MOVE_WINDOW_COMBOBOXITEM,
	"コンテキストメニュー", // LOCALIZATION_ID_OPTIONS_ACTION_CONTEXT_MENU_COMBOBOXITEM,
	"ズームアウト", // LOCALIZATION_ID_OPTIONS_ACTION_ZOOM_OUT_COMBOBOXITEM,
	"前の画像", // LOCALIZATION_ID_OPTIONS_ACTION_PREVIOUS_IMAGE_COMBOBOXITEM,
	"ズーム", // LOCALIZATION_ID_OPTIONS_ACTION_ZOOM_COMBOBOXITEM,
	"次/前", // LOCALIZATION_ID_OPTIONS_ACTION_NEXT_PREV_COMBOBOXITEM,
	"前/次", // LOCALIZATION_ID_OPTIONS_ACTION_PREV_NEXT_COMBOBOXITEM,
	"タイトルバー形式:(&T)", // LOCALIZATION_ID_OPTIONS_TITLE_BAR_FORMAT_STATIC,
	"フルパス", // LOCALIZATION_ID_OPTIONS_TITLE_BAR_FORMAT_FULL_PATH_COMBOBOXITEM,
	"ファイル名のみ", // LOCALIZATION_ID_OPTIONS_TITLE_BAR_FORMAT_FILENAME_ONLY_COMBOBOXITEM,
	"なし", // LOCALIZATION_ID_OPTIONS_TITLE_BAR_FORMAT_NONE_COMBOBOXITEM,
	"Everything が利用できません", // LOCALIZATION_ID_EVERYTHING_NOT_AVAILABLE_MESSAGE,
	"Everything 検索を追加", // LOCALIZATION_ID_EVERYTHING_ADD_EVERYTHING_SEARCH_CAPTION,
	"Everything 検索を読み込み", // LOCALIZATION_ID_EVERYTHING_LOAD_EVERYTHING_SEARCH_CAPTION,
	"ランダム", // LOCALIZATION_ID_RANDOMIZE,
	"コピー先", // LOCALIZATION_ID_COPY_TO_CAPTION,
	"移動先", // LOCALIZATION_ID_MOVE_TO_CAPTION,

	// Association descriptions
	"ビットマップ画像",
	"アニメーションGIF画像",
	"HEIC画像",
	"HEIF画像",
	"アイコンファイル",
	"JPEG画像",
	"JPEG画像",
	"PNG画像",
	"TIFF画像",
	"TIFF画像",
	"WebP画像",
	// LOCALIZATION_ID_ABOUT_PROJECT / LOCALIZATION_ID_ABOUT_PROJECT_URL
	"プロジェクトページ",
	"https://github.com/HaiSeaman/voidImageViewer-i18n",

};
