//
// Copyright 2026 hesphoros
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//
// 한국어 localization
// Save as UTF-8 with BOM (required for MSVC to parse non-ASCII correctly).

const utf8_t *_localization_string_array_ko[LOCALIZATION_ID_COUNT] = 
{
	// Application name
	"한국어", // LOCALIZATION_ID_LANGUAGE

	// Language names (for the language selection menu)
	"English (US)", // LOCALIZATION_ID_LANGUAGE_ENGLISH
	"简体中文", // LOCALIZATION_ID_LANGUAGE_CHINESE_SIMPLIFIED
	"日本語", // LOCALIZATION_ID_LANGUAGE_JAPANESE
	"한국어", // LOCALIZATION_ID_LANGUAGE_KOREAN
	"Français", // LOCALIZATION_ID_LANGUAGE_FRENCH
	"Deutsch", // LOCALIZATION_ID_LANGUAGE_GERMAN
	"Español", // LOCALIZATION_ID_LANGUAGE_SPANISH
	"Português", // LOCALIZATION_ID_LANGUAGE_PORTUGUESE
	"Italiano", // LOCALIZATION_ID_LANGUAGE_ITALIAN
	"العربية", // LOCALIZATION_ID_LANGUAGE_ARABIC
	
	// Application name
	"void Image Viewer", // LOCALIZATION_ID_APP_NAME

	// File menu
	"파일(&F)", // LOCALIZATION_ID_FILE,
	"파일 열기(&O)...", // LOCALIZATION_ID_OPEN_FILE,
	"폴더 열기(&F)...", // LOCALIZATION_ID_OPEN_FOLDER,
	"Everything 검색 열기(&S)...", // LOCALIZATION_ID_OPEN_EVERYTHING_SEARCH,
	"파일 추가(&A)...", // LOCALIZATION_ID_ADD_FILE,
	"폴더 추가...", // LOCALIZATION_ID_ADD_FOLDER,
	"Everything 검색 추가...", // LOCALIZATION_ID_ADD_EVERYTHING_SEARCH,
	"파일 위치 열기(&L)...", // LOCALIZATION_ID_OPEN_FILE_LOCATION,
	"편집(&E)...", // LOCALIZATION_ID_EDIT,
	"미리 보기(&V)...", // LOCALIZATION_ID_PREVIEW,
	"인쇄(&P)...", // LOCALIZATION_ID_PRINT,
	"바탕 화면 배경으로 설정(&D)", // LOCALIZATION_ID_SET_DESKTOP_WALLPAPER,
	"닫기(&C)", // LOCALIZATION_ID_CLOSE,
	"삭제(&D)", // LOCALIZATION_ID_DELETE,
	"삭제(휴지통)", // LOCALIZATION_ID_DELETE_RECYCLE,
	"삭제(영구)", // LOCALIZATION_ID_DELETE_PERMANENTLY,
	"이름 바꾸기(&M)", // LOCALIZATION_ID_RENAME,
	"속성(&R)", // LOCALIZATION_ID_PROPERTIES,
	"종료(&X)", // LOCALIZATION_ID_EXIT,
	
	// Edit menu
	"편집(&E)", // LOCALIZATION_ID_EDIT_MENU,
	"잘라내기(&T)", // LOCALIZATION_ID_CUT,
	"복사(&C)", // LOCALIZATION_ID_COPY,
	"파일 이름 복사", // LOCALIZATION_ID_COPY_FILENAME,
	"이미지 복사(&Y)", // LOCALIZATION_ID_COPY_IMAGE,
	"붙여넣기(&P)", // LOCALIZATION_ID_PASTE,
	"시계 방향 회전(&K)", // LOCALIZATION_ID_ROTATE_CLOCKWISE,
	"반시계 방향 회전(&N)", // LOCALIZATION_ID_ROTATE_COUNTERCLOCKWISE,
	"폴더로 복사(&F)...", // LOCALIZATION_ID_COPY_TO,
	"폴더로 이동(&V)...", // LOCALIZATION_ID_MOVE_TO,
	
	// View menu
	"보기(&V)", // LOCALIZATION_ID_VIEW,
	"캡션", // LOCALIZATION_ID_CAPTION,
	"프레임", // LOCALIZATION_ID_FRAME,
	"메뉴(&M)", // LOCALIZATION_ID_MENU,
	"상태 표시줄(&B)", // LOCALIZATION_ID_STATUS_BAR,
	"컨트롤(&C)", // LOCALIZATION_ID_CONTROLS,
	"프리셋(&P)", // LOCALIZATION_ID_PRESET,
	"최소(&M)", // LOCALIZATION_ID_MINIMAL,
	"간결(&C)", // LOCALIZATION_ID_COMPACT,
	"표준(&N)", // LOCALIZATION_ID_NORMAL,
	"전체 화면(&F)", // LOCALIZATION_ID_FULLSCREEN,
	"슬라이드쇼(&S)", // LOCALIZATION_ID_SLIDESHOW,
	"창 크기(&W)", // LOCALIZATION_ID_VIEW_WINDOW_SIZE,
	"50%", // LOCALIZATION_ID_VIEW_WINDOW_SIZE_50_PERCENT,
	"100%", // LOCALIZATION_ID_VIEW_WINDOW_SIZE_100_PERCENT,
	"200%", // LOCALIZATION_ID_VIEW_WINDOW_SIZE_200_PERCENT,
	"자동 맞춤(&A)", // LOCALIZATION_ID_VIEW_WINDOW_SIZE_AUTO_FIT,
	"새로 고침(&R)", // LOCALIZATION_ID_REFRESH,
	"축소 허용(&A)", // LOCALIZATION_ID_ALLOW_SHRINKING,
	"가로 세로 비율 유지(&K)", // LOCALIZATION_ID_KEEP_ASPECT_RATIO,
	"창에 맞추기(&F)", // LOCALIZATION_ID_FILL_WINDOW,
	"1:1", // LOCALIZATION_ID_ONE_TO_ONE,
	"최적 맞춤(&B)", // LOCALIZATION_ID_BEST_FIT,
	"팬 및 스캔(&N)", // LOCALIZATION_ID_PAN_SCAN,
	"크기 늘리기(&I)", // LOCALIZATION_ID_INCREASE_SIZE,
	"크기 줄이기(&D)", // LOCALIZATION_ID_DECREASE_SIZE,
	"너비 늘리기(&N)", // LOCALIZATION_ID_INCREASE_WIDTH,
	"너비 줄이기(&E)", // LOCALIZATION_ID_DECREASE_WIDTH,
	"높이 늘리기(&C)", // LOCALIZATION_ID_INCREASE_HEIGHT,
	"높이 줄이기(&R)", // LOCALIZATION_ID_DECREASE_HEIGHT,
	"확대/축소(&Z)", // LOCALIZATION_ID_ZOOM,
	"확대(&I)", // LOCALIZATION_ID_ZOOM_IN,
	"축소(&O)", // LOCALIZATION_ID_ZOOM_OUT,
	"초기화(&R)", // LOCALIZATION_ID_RESET,
	"위로 이동(&U)", // LOCALIZATION_ID_MOVE_UP,
	"아래로 이동(&D)", // LOCALIZATION_ID_MOVE_DOWN,
	"왼쪽으로 이동(&L)", // LOCALIZATION_ID_MOVE_LEFT,
	"오른쪽으로 이동(&R)", // LOCALIZATION_ID_MOVE_RIGHT,
	"왼쪽 위로 이동", // LOCALIZATION_ID_MOVE_UP_LEFT,
	"오른쪽 위로 이동", // LOCALIZATION_ID_MOVE_UP_RIGHT,
	"왼쪽 아래로 이동", // LOCALIZATION_ID_MOVE_DOWN_LEFT,
	"오른쪽 아래로 이동", // LOCALIZATION_ID_MOVE_DOWN_RIGHT,
	"중앙으로 이동(&T)", // LOCALIZATION_ID_MOVE_CENTER,
	"초기화(&S)", // LOCALIZATION_ID_PANSCAN_RESET,
	"항상 위(&T)", // LOCALIZATION_ID_ON_TOP,
	"항상(&A)", // LOCALIZATION_ID_ALWAYS,
	"슬라이드쇼 또는 애니메이션 재생 중(&W)", // LOCALIZATION_ID_WHILE_PLAYING_OR_ANIMATING,
	"안 함(&N)", // LOCALIZATION_ID_NEVER,
	"옵션(&O)...", // LOCALIZATION_ID_OPTIONS,
	"전환(&T)", // LOCALIZATION_ID_TRANSITION,
	"없음(&N)", // LOCALIZATION_ID_TRANSITION_NONE,
	"페이드(&F)", // LOCALIZATION_ID_TRANSITION_FADE,
	"시간...", // LOCALIZATION_ID_TRANSITION_DURATION,
	
	// Slideshow menu
	"슬라이드쇼(&S)", // LOCALIZATION_ID_SLIDESHOW_MENU,
	"재생/일시 정지(&P)", // LOCALIZATION_ID_PLAY_PAUSE,
	"속도(&R)", // LOCALIZATION_ID_RATE,
	"속도 줄이기(&D)", // LOCALIZATION_ID_DECREASE_RATE,
	"속도 늘리기(&I)", // LOCALIZATION_ID_INCREASE_RATE,
	"250 밀리초", // LOCALIZATION_ID_RATE_250_MILLISECONDS,
	"500 밀리초", // LOCALIZATION_ID_RATE_500_MILLISECONDS,
	"1초(&1)", // LOCALIZATION_ID_RATE_1_SECOND,
	"2초(&2)", // LOCALIZATION_ID_RATE_2_SECONDS,
	"3초(&3)", // LOCALIZATION_ID_RATE_3_SECONDS,
	"4초(&4)", // LOCALIZATION_ID_RATE_4_SECONDS,
	"5초(&5)", // LOCALIZATION_ID_RATE_5_SECONDS,
	"6초(&6)", // LOCALIZATION_ID_RATE_6_SECONDS,
	"7초(&7)", // LOCALIZATION_ID_RATE_7_SECONDS,
	"8초(&8)", // LOCALIZATION_ID_RATE_8_SECONDS,
	"9초(&9)", // LOCALIZATION_ID_RATE_9_SECONDS,
	"10초(&0)", // LOCALIZATION_ID_RATE_10_SECONDS,
	"20초", // LOCALIZATION_ID_RATE_20_SECONDS,
	"30초", // LOCALIZATION_ID_RATE_30_SECONDS,
	"40초", // LOCALIZATION_ID_RATE_40_SECONDS,
	"50초", // LOCALIZATION_ID_RATE_50_SECONDS,
	"1분",	// LOCALIZATION_ID_RATE_1_MINUTE,
	"사용자 지정...", // LOCALIZATION_ID_CUSTOM,
	"애니메이션 시간(&D)", // LOCALIZATION_ID_RATE_ANIMATION_DURATION,
	
	// Animation menu
	"애니메이션(&A)", // LOCALIZATION_ID_ANIMATION,
	"재생/일시 정지(&P)", // LOCALIZATION_ID_ANIMATION_PLAY_PAUSE,
	"앞으로 이동(&F)", // LOCALIZATION_ID_ANIMATION_JUMP_FORWARD,
	"뒤로 이동(&B)", // LOCALIZATION_ID_ANIMATION_JUMP_BACKWARD,
	"짧게 앞으로 이동(&F)", // LOCALIZATION_ID_ANIMATION_SHORT_JUMP_FORWARD,
	"짧게 뒤로 이동(&B)", // LOCALIZATION_ID_ANIMATION_SHORT_JUMP_BACKWARD,
	"길게 앞으로 이동(&F)", // LOCALIZATION_ID_ANIMATION_LONG_JUMP_FORWARD,
	"길게 뒤로 이동(&B)", // LOCALIZATION_ID_ANIMATION_LONG_JUMP_BACKWARD,
	"프레임 단계(&R)", // LOCALIZATION_ID_ANIMATION_FRAME_STEP,
	"이전 프레임(&V)", // LOCALIZATION_ID_ANIMATION_PREVIOUS_FRAME,
	"첫 프레임(&F)", // LOCALIZATION_ID_ANIMATION_FIRST_FRAME,
	"마지막 프레임(&L)", // LOCALIZATION_ID_ANIMATION_LAST_FRAME,
	"속도 줄이기(&D)", // LOCALIZATION_ID_ANIMATION_DECREASE_RATE,
	"속도 늘리기(&I)", // LOCALIZATION_ID_ANIMATION_INCREASE_RATE,
	"속도 초기화(&R)", // LOCALIZATION_ID_ANIMATION_RESET_RATE,
	
	// Navigate menu
	"탐색(&N)", // LOCALIZATION_ID_NAVIGATE,
	"다음(&N)", // LOCALIZATION_ID_NEXT,
	"이전(&R)", // LOCALIZATION_ID_PREVIOUS,
	"홈(&H)", // LOCALIZATION_ID_HOME,
	"끝(&E)", // LOCALIZATION_ID_END,
	"정렬(&S)", // LOCALIZATION_ID_SORT,
	"이름(&N)", // LOCALIZATION_ID_SORT_NAME,
	"전체 경로(&P)", // LOCALIZATION_ID_SORT_FULL_PATH,
	"크기(&S)", // LOCALIZATION_ID_SORT_SIZE,
	"수정한 날짜(&M)", // LOCALIZATION_ID_SORT_DATE_MODIFIED,
	"만든 날짜(&C)", // LOCALIZATION_ID_SORT_DATE_CREATED,
	"오름차순(&A)", // LOCALIZATION_ID_SORT_ASCENDING,
	"내림차순(&D)", // LOCALIZATION_ID_SORT_DESCENDING,
	"셔플", // LOCALIZATION_ID_SHUFFLE,
	"이동(&J)...", // LOCALIZATION_ID_JUMP_TO,
	
	// Help menu
	"도움말(&H)", // LOCALIZATION_ID_HELP,
	"도움말(&H)", // LOCALIZATION_ID_HELP_MENU,
	"명령줄 옵션(&C)", // LOCALIZATION_ID_COMMAND_LINE_OPTIONS,
	"홈페이지(&P)", // LOCALIZATION_ID_HOME_PAGE,
	"기부(&D)", // LOCALIZATION_ID_DONATE,
	"정보(&A)", // LOCALIZATION_ID_ABOUT,
	"https://www.voidtools.com/support/voidimageviewer/", // LOCALIZATION_ID_HELP_SUPPORT_URL,
	"https://www.voidtools.com/donate/", // LOCALIZATION_ID_HELP_DONATE_URL,
	"https://www.voidtools.com/", // LOCALIZATION_ID_HELP_WEBSITE_URL,

	// Toolbar
	"이전 이미지", // LOCALIZATION_ID_TOOLBAR_PREVIOUS_IMAGE_BUTTON,
	"다음 이미지", // LOCALIZATION_ID_TOOLBAR_NEXT_IMAGE_BUTTON,
	"슬라이드쇼 재생", // LOCALIZATION_ID_TOOLBAR_PLAY_SLIDESHOW_BUTTON,
	"슬라이드쇼 일시 정지", // LOCALIZATION_ID_TOOLBAR_PAUSE_SLIDESHOW_BUTTON,
	"최적 맞춤", // LOCALIZATION_ID_TOOLBAR_BEST_FIT_BUTTON,
	"실제 크기", // LOCALIZATION_ID_TOOLBAR_ACTUAL_SIZE_BUTTON,

	// Status bar
	"PRELOAD", // LOCALIZATION_ID_STATUS_BAR_PRELOAD,
	"로드 중...", // LOCALIZATION_ID_STATUS_BAR_LOADING,
	"파일을 찾을 수 없습니다.", // LOCALIZATION_ID_STATUS_BAR_FILE_NOT_FOUND,
	"이미지를 로드하지 못했습니다.", // LOCALIZATION_ID_STATUS_BAR_FAILED_TO_LOAD_IMAGE,
	"슬라이드쇼 재생 중", // LOCALIZATION_ID_STATUS_BAR_SLIDESHOW_PLAYING,
	"위치 %0.3f %0.3f, 확대 %0.3f %0.3f, 가로 세로 비율 %0.3f", // LOCALIZATION_ID_STATUS_BAR_POS_ZOOM_FORMAT,
	"애니메이션 속도 %0.3f", // LOCALIZATION_ID_STATUS_BAR_ANIMATION_RATE_FORMAT,
	"슬라이드쇼 속도 %d %s", // LOCALIZATION_ID_STATUS_BAR_SLIDESHOW_RATE_FORMAT,
	"슬라이드쇼 속도: 애니메이션 시간", // LOCALIZATION_ID_STATUS_BAR_ANIMATION_DURATION,
	"분", // LOCALIZATION_ID_STATUS_BAR_MINUTES,
	"초", // LOCALIZATION_ID_STATUS_BAR_SECONDS,
	"밀리초", // LOCALIZATION_ID_STATUS_BAR_MILLISECONDS,

	// Dialog strings
	"옵션 - void Image Viewer", // LOCALIZATION_ID_OPTIONS_CAPTION,
	"일반", // LOCALIZATION_ID_OPTIONS_GENERAL_DIALOG,
	"보기", // LOCALIZATION_ID_OPTIONS_VIEW_DIALOG,
	"컨트롤", // LOCALIZATION_ID_OPTIONS_CONTROLS_DIALOG,
	"확인", // LOCALIZATION_ID_OK_BUTTON,
	"취소", // LOCALIZATION_ID_CANCEL_BUTTON,
	"설정을 %APPDATA%\\voidImageViewer에 저장(&S)", // LOCALIZATION_ID_STORE_SETTINGS_APPDATA,
	"여러 인스턴스 허용(&I)", // LOCALIZATION_ID_ALLOW_MULTIPLE_INSTANCES,
	"시작 메뉴 바로 가기(&M)", // LOCALIZATION_ID_STARTMENU_SHORTCUTS,
	"연결", // LOCALIZATION_ID_ASSOCIATIONS,
	"모두 선택(&A)", // LOCALIZATION_ID_CHECK_ALL,
	"모두 해제(&N)", // LOCALIZATION_ID_CHECK_NONE,
	"축소 블릿 모드:(&S)", // LOCALIZATION_ID_SHRINK_BLIT_MODE_STATIC,
	"확대 블릿 모드:(&M)", // LOCALIZATION_ID_MAGNIFY_BLIT_MODE,
	"최근접", // LOCALIZATION_ID_BLIT_MODE_NEAREST_COMBOBOXITEM,
	"선형", // LOCALIZATION_ID_BLIT_MODE_LINEAR_COMBOBOXITEM,
	"창 자동 크기:(&Z)", // LOCALIZATION_ID_OPTIONS_VIEW_AUTO_SIZE_WINDOW_STATIC,
	"50%", // LOCALIZATION_ID_OPTIONS_VIEW_AUTO_SIZE_WINDOW_50_PERCENT_COMBOBOXITEM,
	"100%", // LOCALIZATION_ID_OPTIONS_VIEW_AUTO_SIZE_WINDOW_100_PERCENT_COMBOBOXITEM,
	"200%", // LOCALIZATION_ID_OPTIONS_VIEW_AUTO_SIZE_WINDOW_200_PERCENT_COMBOBOXITEM,
	"자동 맞춤", // LOCALIZATION_ID_OPTIONS_VIEW_AUTO_SIZE_WINDOW_AUTO_FIT_COMBOBOXITEM,
	"슬라이드쇼에서 애니메이션을 최소 1회 재생(&P)", // LOCALIZATION_ID_PLAY_ANIMATIONS_ONCE_STATIC,
	"다음 이미지 미리 로드(&N)", // LOCALIZATION_ID_PRELOAD_NEXT_IMAGE_STATIC,
	"마지막 이미지 캐시(&L)", // LOCALIZATION_ID_CACHE_LAST_IMAGE_STATIC,
	"창 배경색:(&W)", // LOCALIZATION_ID_WINDOWED_BACKGROUND_COLOR_STATIC,
	"전체 화면 배경색:(&F)", // LOCALIZATION_ID_FULLSCREEN_BACKGROUND_COLOR_STATIC,
	"왼쪽 클릭 동작:(&L)", // LOCALIZATION_ID_LEFT_CLICK_ACTION_STATIC,
	"오른쪽 클릭 동작:(&R)", // LOCALIZATION_ID_RIGHT_CLICK_ACTION_STATIC,
	"마우스 휠 동작:(&M)", // LOCALIZATION_ID_MOUSE_WHEEL_ACTION_STATIC,
	"명령:(&C)", // LOCALIZATION_ID_COMMANDS_STATIC,
	"선택한 명령의 설정", // LOCALIZATION_ID_SETTINGS_FOR_SELECTED_COMMAND,
	"추가(&A)...", // LOCALIZATION_ID_ADD_KEY_BUTTON,
	"편집(&E)...", // LOCALIZATION_ID_EDIT_KEY_BUTTON,
	"제거(&V)", // LOCALIZATION_ID_REMOVE_KEY_BUTTON,
	"키보드 바로 가기 추가", // LOCALIZATION_ID_ADD_KEYBOARD_SHORTCUT_CAPTION,
	"키보드 바로 가기 편집", // LOCALIZATION_ID_EDIT_KEYBOARD_SHORTCUT_CAPTION,
	"바로 가기 키:(&K)", // LOCALIZATION_ID_SHORTCUT_KEY,
	"바로 가기 키가 사용 중:", // LOCALIZATION_ID_SHORTCUT_KEY_CURRENTLY_USED_BY,
	"사용자 지정 속도 설정", // LOCALIZATION_ID_SET_CUSTOM_RATE_CAPTION,
	"사용자 지정 속도:(&C)", // LOCALIZATION_ID_CUSTOM_RATE_STATIC,
	"분", // LOCALIZATION_ID_CUSTOM_RATE_MINUTES,
	"초", // LOCALIZATION_ID_CUSTOM_RATE_SECONDS,
	"밀리초", // LOCALIZATION_ID_CUSTOM_RATE_MILLISECONDS,
	"void Image Viewer 정보", // LOCALIZATION_ID_ABOUT_CAPTION,
	"이름 바꾸기", // LOCALIZATION_ID_RENAME_CAPTION,
	"이동", // LOCALIZATION_ID_JUMP_TO_TITLE,
	"Copyright © %d voidtools", // LOCALIZATION_ID_ABOUT_COPYRIGHT_FORMAT,
	"support@voidtools.com", // LOCALIZATION_ID_ABOUT_EMAIL,
	"www.voidtools.com", // LOCALIZATION_ID_ABOUT_WEBSITE,
	"이미지 열기", // LOCALIZATION_ID_OPEN_IMAGE_CAPTION,
	"모든 이미지 파일", // LOCALIZATION_ID_OPEN_ALL_IMAGE_FILES,
	"모든 파일", // LOCALIZATION_ID_OPEN_ALL_FILES,
	"스크롤", // LOCALIZATION_ID_OPTIONS_ACTION_SCROLL_COMBOBOXITEM,
	"슬라이드쇼 재생/일시 정지", // LOCALIZATION_ID_OPTIONS_ACTION_PLAY_PAUSE_SLIDESHOW_COMBOBOXITEM,
	"애니메이션 재생/일시 정지", // LOCALIZATION_ID_OPTIONS_ACTION_PLAY_PAUSE_ANIMATION_COMBOBOXITEM,
	"확대", // LOCALIZATION_ID_OPTIONS_ACTION_ZOOM_IN_COMBOBOXITEM,
	"다음 이미지", // LOCALIZATION_ID_OPTIONS_ACTION_NEXT_IMAGE_COMBOBOXITEM,
	"1:1 스크롤", // LOCALIZATION_ID_OPTIONS_ACTION_ONE_TO_ONE_SCROLL_COMBOBOXITEM,
	"스크롤/창 이동", // LOCALIZATION_ID_OPTIONS_ACTION_SCROLL_MOVE_WINDOW_COMBOBOXITEM,
	"컨텍스트 메뉴", // LOCALIZATION_ID_OPTIONS_ACTION_CONTEXT_MENU_COMBOBOXITEM,
	"축소", // LOCALIZATION_ID_OPTIONS_ACTION_ZOOM_OUT_COMBOBOXITEM,
	"이전 이미지", // LOCALIZATION_ID_OPTIONS_ACTION_PREVIOUS_IMAGE_COMBOBOXITEM,
	"확대/축소", // LOCALIZATION_ID_OPTIONS_ACTION_ZOOM_COMBOBOXITEM,
	"다음/이전", // LOCALIZATION_ID_OPTIONS_ACTION_NEXT_PREV_COMBOBOXITEM,
	"이전/다음", // LOCALIZATION_ID_OPTIONS_ACTION_PREV_NEXT_COMBOBOXITEM,
	"제목 표시줄 형식:(&T)", // LOCALIZATION_ID_OPTIONS_TITLE_BAR_FORMAT_STATIC,
	"전체 경로", // LOCALIZATION_ID_OPTIONS_TITLE_BAR_FORMAT_FULL_PATH_COMBOBOXITEM,
	"파일 이름만", // LOCALIZATION_ID_OPTIONS_TITLE_BAR_FORMAT_FILENAME_ONLY_COMBOBOXITEM,
	"없음", // LOCALIZATION_ID_OPTIONS_TITLE_BAR_FORMAT_NONE_COMBOBOXITEM,
	"Everything을 사용할 수 없습니다", // LOCALIZATION_ID_EVERYTHING_NOT_AVAILABLE_MESSAGE,
	"Everything 검색 추가", // LOCALIZATION_ID_EVERYTHING_ADD_EVERYTHING_SEARCH_CAPTION,
	"Everything 검색 로드", // LOCALIZATION_ID_EVERYTHING_LOAD_EVERYTHING_SEARCH_CAPTION,
	"무작위", // LOCALIZATION_ID_RANDOMIZE,
	"복사 대상", // LOCALIZATION_ID_COPY_TO_CAPTION,
	"이동 대상", // LOCALIZATION_ID_MOVE_TO_CAPTION,

	// Association descriptions
	"비트맵 이미지",
	"애니메이션 GIF 이미지",
	"HEIC 이미지",
	"HEIF 이미지",
	"아이콘 파일",
	"JPEG 이미지",
	"JPEG 이미지",
	"PNG 이미지",
	"TIFF 이미지",
	"TIFF 이미지",
	"WebP 이미지",
};
