//
// Copyright 2026 hesphoros
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//
// العربية localization
// Save as UTF-8 with BOM (required for MSVC to parse non-ASCII correctly).

const utf8_t *_localization_string_array_ar[LOCALIZATION_ID_COUNT] = 
{
	// Application name
	"العربية", // LOCALIZATION_ID_LANGUAGE

	// Language names (for the language selection menu)
	"English (US)", // LOCALIZATION_ID_LANGUAGE_ENGLISH
	"简体中文", // LOCALIZATION_ID_LANGUAGE_CHINESE_SIMPLIFIED
	"日本語", // LOCALIZATION_ID_LANGUAGE_JAPANESE
	"한국어", // LOCALIZATION_ID_LANGUAGE_KOREAN
	"Français", // LOCALIZATION_ID_LANGUAGE_FRENCH
	"Deutsch", // LOCALIZATION_ID_LANGUAGE_GERMAN
	"Español", // LOCALIZATION_ID_LANGUAGE_SPANISH
	"Português", // LOCALIZATION_ID_LANGUAGE_PORTUGUESE
	"Italiano", // LOCALIZATION_ID_LANGUAGE_ITALIAN
	"العربية", // LOCALIZATION_ID_LANGUAGE_ARABIC
	
	// Application name
	"void Image Viewer", // LOCALIZATION_ID_APP_NAME

	// File menu
	"ملف", // LOCALIZATION_ID_FILE,
	"فتح ملف...", // LOCALIZATION_ID_OPEN_FILE,
	"فتح مجلد...", // LOCALIZATION_ID_OPEN_FOLDER,
	"فتح بحث Everything...", // LOCALIZATION_ID_OPEN_EVERYTHING_SEARCH,
	"إضافة ملف...", // LOCALIZATION_ID_ADD_FILE,
	"إضافة مجلد...", // LOCALIZATION_ID_ADD_FOLDER,
	"إضافة بحث Everything...", // LOCALIZATION_ID_ADD_EVERYTHING_SEARCH,
	"فتح موقع الملف...", // LOCALIZATION_ID_OPEN_FILE_LOCATION,
	"تعديل...", // LOCALIZATION_ID_EDIT,
	"معاينة...", // LOCALIZATION_ID_PREVIEW,
	"طباعة...", // LOCALIZATION_ID_PRINT,
	"تعيين كخلفية سطح المكتب", // LOCALIZATION_ID_SET_DESKTOP_WALLPAPER,
	"إغلاق", // LOCALIZATION_ID_CLOSE,
	"حذف", // LOCALIZATION_ID_DELETE,
	"حذف (سلة المحذوفات)", // LOCALIZATION_ID_DELETE_RECYCLE,
	"حذف (نهائي)", // LOCALIZATION_ID_DELETE_PERMANENTLY,
	"إعادة تسمية", // LOCALIZATION_ID_RENAME,
	"خصائص", // LOCALIZATION_ID_PROPERTIES,
	"خروج", // LOCALIZATION_ID_EXIT,
	
	// Edit menu
	"تعديل", // LOCALIZATION_ID_EDIT_MENU,
	"قص", // LOCALIZATION_ID_CUT,
	"نسخ", // LOCALIZATION_ID_COPY,
	"نسخ اسم الملف", // LOCALIZATION_ID_COPY_FILENAME,
	"نسخ الصورة", // LOCALIZATION_ID_COPY_IMAGE,
	"لصق", // LOCALIZATION_ID_PASTE,
	"تدوير باتجاه عقارب الساعة", // LOCALIZATION_ID_ROTATE_CLOCKWISE,
	"تدوير عكس عقارب الساعة", // LOCALIZATION_ID_ROTATE_COUNTERCLOCKWISE,
	"نسخ إلى مجلد...", // LOCALIZATION_ID_COPY_TO,
	"نقل إلى مجلد...", // LOCALIZATION_ID_MOVE_TO,
	
	// View menu
	"عرض", // LOCALIZATION_ID_VIEW,
	"تسمية توضيحية", // LOCALIZATION_ID_CAPTION,
	"إطار", // LOCALIZATION_ID_FRAME,
	"قائمة", // LOCALIZATION_ID_MENU,
	"شريط الحالة", // LOCALIZATION_ID_STATUS_BAR,
	"عناصر التحكم", // LOCALIZATION_ID_CONTROLS,
	"إعداد مسبق", // LOCALIZATION_ID_PRESET,
	"أدنى حد", // LOCALIZATION_ID_MINIMAL,
	"مضغوط", // LOCALIZATION_ID_COMPACT,
	"عادي", // LOCALIZATION_ID_NORMAL,
	"ملء الشاشة", // LOCALIZATION_ID_FULLSCREEN,
	"عرض الشرائح", // LOCALIZATION_ID_SLIDESHOW,
	"حجم النافذة", // LOCALIZATION_ID_VIEW_WINDOW_SIZE,
	"50%", // LOCALIZATION_ID_VIEW_WINDOW_SIZE_50_PERCENT,
	"100%", // LOCALIZATION_ID_VIEW_WINDOW_SIZE_100_PERCENT,
	"200%", // LOCALIZATION_ID_VIEW_WINDOW_SIZE_200_PERCENT,
	"ملاءمة تلقائية", // LOCALIZATION_ID_VIEW_WINDOW_SIZE_AUTO_FIT,
	"تحديث", // LOCALIZATION_ID_REFRESH,
	"السماح بالتصغير", // LOCALIZATION_ID_ALLOW_SHRINKING,
	"الحفاظ على نسبة الأبعاد", // LOCALIZATION_ID_KEEP_ASPECT_RATIO,
	"ملء النافذة", // LOCALIZATION_ID_FILL_WINDOW,
	"1:1", // LOCALIZATION_ID_ONE_TO_ONE,
	"أفضل ملاءمة", // LOCALIZATION_ID_BEST_FIT,
	"تحريك ومسح", // LOCALIZATION_ID_PAN_SCAN,
	"زيادة الحجم", // LOCALIZATION_ID_INCREASE_SIZE,
	"تقليل الحجم", // LOCALIZATION_ID_DECREASE_SIZE,
	"زيادة العرض", // LOCALIZATION_ID_INCREASE_WIDTH,
	"تقليل العرض", // LOCALIZATION_ID_DECREASE_WIDTH,
	"زيادة الارتفاع", // LOCALIZATION_ID_INCREASE_HEIGHT,
	"تقليل الارتفاع", // LOCALIZATION_ID_DECREASE_HEIGHT,
	"تكبير/تصغير", // LOCALIZATION_ID_ZOOM,
	"تكبير", // LOCALIZATION_ID_ZOOM_IN,
	"تصغير", // LOCALIZATION_ID_ZOOM_OUT,
	"إعادة تعيين", // LOCALIZATION_ID_RESET,
	"تحريك لأعلى", // LOCALIZATION_ID_MOVE_UP,
	"تحريك لأسفل", // LOCALIZATION_ID_MOVE_DOWN,
	"تحريك لليسار", // LOCALIZATION_ID_MOVE_LEFT,
	"تحريك لليمين", // LOCALIZATION_ID_MOVE_RIGHT,
	"تحريك لأعلى اليسار", // LOCALIZATION_ID_MOVE_UP_LEFT,
	"تحريك لأعلى اليمين", // LOCALIZATION_ID_MOVE_UP_RIGHT,
	"تحريك لأسفل اليسار", // LOCALIZATION_ID_MOVE_DOWN_LEFT,
	"تحريك لأسفل اليمين", // LOCALIZATION_ID_MOVE_DOWN_RIGHT,
	"تحريك للمنتصف", // LOCALIZATION_ID_MOVE_CENTER,
	"إعادة تعيين", // LOCALIZATION_ID_PANSCAN_RESET,
	"دائمًا في المقدمة", // LOCALIZATION_ID_ON_TOP,
	"دائمًا", // LOCALIZATION_ID_ALWAYS,
	"أثناء تشغيل عرض الشرائح أو الرسوم المتحركة", // LOCALIZATION_ID_WHILE_PLAYING_OR_ANIMATING,
	"أبدًا", // LOCALIZATION_ID_NEVER,
	"خيارات...", // LOCALIZATION_ID_OPTIONS,
	"انتقال", // LOCALIZATION_ID_TRANSITION,
	"لا شيء", // LOCALIZATION_ID_TRANSITION_NONE,
	"تلاشي", // LOCALIZATION_ID_TRANSITION_FADE,
	"المدة...", // LOCALIZATION_ID_TRANSITION_DURATION,
	
	// Slideshow menu
	"عرض الشرائح", // LOCALIZATION_ID_SLIDESHOW_MENU,
	"تشغيل/إيقاف مؤقت", // LOCALIZATION_ID_PLAY_PAUSE,
	"السرعة", // LOCALIZATION_ID_RATE,
	"تقليل السرعة", // LOCALIZATION_ID_DECREASE_RATE,
	"زيادة السرعة", // LOCALIZATION_ID_INCREASE_RATE,
	"250 مللي ثانية", // LOCALIZATION_ID_RATE_250_MILLISECONDS,
	"500 مللي ثانية", // LOCALIZATION_ID_RATE_500_MILLISECONDS,
	"1 ثانية", // LOCALIZATION_ID_RATE_1_SECOND,
	"2 ثانيتين", // LOCALIZATION_ID_RATE_2_SECONDS,
	"3 ثوانٍ", // LOCALIZATION_ID_RATE_3_SECONDS,
	"4 ثوانٍ", // LOCALIZATION_ID_RATE_4_SECONDS,
	"5 ثوانٍ", // LOCALIZATION_ID_RATE_5_SECONDS,
	"6 ثوانٍ", // LOCALIZATION_ID_RATE_6_SECONDS,
	"7 ثوانٍ", // LOCALIZATION_ID_RATE_7_SECONDS,
	"8 ثوانٍ", // LOCALIZATION_ID_RATE_8_SECONDS,
	"9 ثوانٍ", // LOCALIZATION_ID_RATE_9_SECONDS,
	"10 ثوانٍ", // LOCALIZATION_ID_RATE_10_SECONDS,
	"20 ثانية", // LOCALIZATION_ID_RATE_20_SECONDS,
	"30 ثانية", // LOCALIZATION_ID_RATE_30_SECONDS,
	"40 ثانية", // LOCALIZATION_ID_RATE_40_SECONDS,
	"50 ثانية", // LOCALIZATION_ID_RATE_50_SECONDS,
	"1 دقيقة",	// LOCALIZATION_ID_RATE_1_MINUTE,
	"مخصص...", // LOCALIZATION_ID_CUSTOM,
	"مدة الرسوم المتحركة", // LOCALIZATION_ID_RATE_ANIMATION_DURATION,
	
	// Animation menu
	"رسوم متحركة", // LOCALIZATION_ID_ANIMATION,
	"تشغيل/إيقاف مؤقت", // LOCALIZATION_ID_ANIMATION_PLAY_PAUSE,
	"قفز للأمام", // LOCALIZATION_ID_ANIMATION_JUMP_FORWARD,
	"قفز للخلف", // LOCALIZATION_ID_ANIMATION_JUMP_BACKWARD,
	"قفز قصير للأمام", // LOCALIZATION_ID_ANIMATION_SHORT_JUMP_FORWARD,
	"قفز قصير للخلف", // LOCALIZATION_ID_ANIMATION_SHORT_JUMP_BACKWARD,
	"قفز طويل للأمام", // LOCALIZATION_ID_ANIMATION_LONG_JUMP_FORWARD,
	"قفز طويل للخلف", // LOCALIZATION_ID_ANIMATION_LONG_JUMP_BACKWARD,
	"خطوة إطار", // LOCALIZATION_ID_ANIMATION_FRAME_STEP,
	"الإطار السابق", // LOCALIZATION_ID_ANIMATION_PREVIOUS_FRAME,
	"الإطار الأول", // LOCALIZATION_ID_ANIMATION_FIRST_FRAME,
	"الإطار الأخير", // LOCALIZATION_ID_ANIMATION_LAST_FRAME,
	"تقليل السرعة", // LOCALIZATION_ID_ANIMATION_DECREASE_RATE,
	"زيادة السرعة", // LOCALIZATION_ID_ANIMATION_INCREASE_RATE,
	"إعادة تعيين السرعة", // LOCALIZATION_ID_ANIMATION_RESET_RATE,
	
	// Navigate menu
	"تنقل", // LOCALIZATION_ID_NAVIGATE,
	"التالي", // LOCALIZATION_ID_NEXT,
	"السابق", // LOCALIZATION_ID_PREVIOUS,
	"البداية", // LOCALIZATION_ID_HOME,
	"النهاية", // LOCALIZATION_ID_END,
	"فرز", // LOCALIZATION_ID_SORT,
	"الاسم", // LOCALIZATION_ID_SORT_NAME,
	"المسار الكامل", // LOCALIZATION_ID_SORT_FULL_PATH,
	"الحجم", // LOCALIZATION_ID_SORT_SIZE,
	"تاريخ التعديل", // LOCALIZATION_ID_SORT_DATE_MODIFIED,
	"تاريخ الإنشاء", // LOCALIZATION_ID_SORT_DATE_CREATED,
	"تصاعدي", // LOCALIZATION_ID_SORT_ASCENDING,
	"تنازلي", // LOCALIZATION_ID_SORT_DESCENDING,
	"خلط", // LOCALIZATION_ID_SHUFFLE,
	"الانتقال إلى...", // LOCALIZATION_ID_JUMP_TO,
	
	// Help menu
	"مساعدة", // LOCALIZATION_ID_HELP,
	"مساعدة", // LOCALIZATION_ID_HELP_MENU,
	"خيارات سطر الأوامر", // LOCALIZATION_ID_COMMAND_LINE_OPTIONS,
	"الصفحة الرئيسية", // LOCALIZATION_ID_HOME_PAGE,
	"تبرع", // LOCALIZATION_ID_DONATE,
	"حول", // LOCALIZATION_ID_ABOUT,
	"https://www.voidtools.com/support/voidimageviewer/", // LOCALIZATION_ID_HELP_SUPPORT_URL,
	"https://www.voidtools.com/donate/", // LOCALIZATION_ID_HELP_DONATE_URL,
	"https://www.voidtools.com/", // LOCALIZATION_ID_HELP_WEBSITE_URL,

	// Toolbar
	"الصورة السابقة", // LOCALIZATION_ID_TOOLBAR_PREVIOUS_IMAGE_BUTTON,
	"الصورة التالية", // LOCALIZATION_ID_TOOLBAR_NEXT_IMAGE_BUTTON,
	"تشغيل عرض الشرائح", // LOCALIZATION_ID_TOOLBAR_PLAY_SLIDESHOW_BUTTON,
	"إيقاف عرض الشرائح مؤقتًا", // LOCALIZATION_ID_TOOLBAR_PAUSE_SLIDESHOW_BUTTON,
	"أفضل ملاءمة", // LOCALIZATION_ID_TOOLBAR_BEST_FIT_BUTTON,
	"الحجم الفعلي", // LOCALIZATION_ID_TOOLBAR_ACTUAL_SIZE_BUTTON,

	// Status bar
	"PRELOAD", // LOCALIZATION_ID_STATUS_BAR_PRELOAD,
	"جارٍ التحميل...", // LOCALIZATION_ID_STATUS_BAR_LOADING,
	"الملف غير موجود.", // LOCALIZATION_ID_STATUS_BAR_FILE_NOT_FOUND,
	"فشل تحميل الصورة.", // LOCALIZATION_ID_STATUS_BAR_FAILED_TO_LOAD_IMAGE,
	"عرض الشرائح قيد التشغيل", // LOCALIZATION_ID_STATUS_BAR_SLIDESHOW_PLAYING,
	"الموضع %0.3f %0.3f، التكبير %0.3f %0.3f، نسبة الأبعاد %0.3f", // LOCALIZATION_ID_STATUS_BAR_POS_ZOOM_FORMAT,
	"سرعة الرسوم المتحركة %0.3f", // LOCALIZATION_ID_STATUS_BAR_ANIMATION_RATE_FORMAT,
	"سرعة عرض الشرائح %d %s", // LOCALIZATION_ID_STATUS_BAR_SLIDESHOW_RATE_FORMAT,
	"سرعة عرض الشرائح: مدة الرسوم المتحركة", // LOCALIZATION_ID_STATUS_BAR_ANIMATION_DURATION,
	"دقائق", // LOCALIZATION_ID_STATUS_BAR_MINUTES,
	"ثوانٍ", // LOCALIZATION_ID_STATUS_BAR_SECONDS,
	"مللي ثانية", // LOCALIZATION_ID_STATUS_BAR_MILLISECONDS,

	// Dialog strings
	"خيارات - void Image Viewer", // LOCALIZATION_ID_OPTIONS_CAPTION,
	"عام", // LOCALIZATION_ID_OPTIONS_GENERAL_DIALOG,
	"عرض", // LOCALIZATION_ID_OPTIONS_VIEW_DIALOG,
	"عناصر التحكم", // LOCALIZATION_ID_OPTIONS_CONTROLS_DIALOG,
	"موافق", // LOCALIZATION_ID_OK_BUTTON,
	"إلغاء", // LOCALIZATION_ID_CANCEL_BUTTON,
	"حفظ الإعدادات في %APPDATA%\\voidImageViewer", // LOCALIZATION_ID_STORE_SETTINGS_APPDATA,
	"السماح بوجود مثيلات متعددة", // LOCALIZATION_ID_ALLOW_MULTIPLE_INSTANCES,
	"اختصارات قائمة ابدأ", // LOCALIZATION_ID_STARTMENU_SHORTCUTS,
	"الارتباطات", // LOCALIZATION_ID_ASSOCIATIONS,
	"تحديد الكل", // LOCALIZATION_ID_CHECK_ALL,
	"إلغاء تحديد الكل", // LOCALIZATION_ID_CHECK_NONE,
	"وضع بلت التصغير:", // LOCALIZATION_ID_SHRINK_BLIT_MODE_STATIC,
	"وضع بلت التكبير:", // LOCALIZATION_ID_MAGNIFY_BLIT_MODE,
	"الأقرب", // LOCALIZATION_ID_BLIT_MODE_NEAREST_COMBOBOXITEM,
	"خطي", // LOCALIZATION_ID_BLIT_MODE_LINEAR_COMBOBOXITEM,
	"حجم النافذة التلقائي:", // LOCALIZATION_ID_OPTIONS_VIEW_AUTO_SIZE_WINDOW_STATIC,
	"50%", // LOCALIZATION_ID_OPTIONS_VIEW_AUTO_SIZE_WINDOW_50_PERCENT_COMBOBOXITEM,
	"100%", // LOCALIZATION_ID_OPTIONS_VIEW_AUTO_SIZE_WINDOW_100_PERCENT_COMBOBOXITEM,
	"200%", // LOCALIZATION_ID_OPTIONS_VIEW_AUTO_SIZE_WINDOW_200_PERCENT_COMBOBOXITEM,
	"ملاءمة تلقائية", // LOCALIZATION_ID_OPTIONS_VIEW_AUTO_SIZE_WINDOW_AUTO_FIT_COMBOBOXITEM,
	"تشغيل الرسوم المتحركة مرة واحدة على الأقل في عرض الشرائح", // LOCALIZATION_ID_PLAY_ANIMATIONS_ONCE_STATIC,
	"تحميل الصورة التالية مسبقًا", // LOCALIZATION_ID_PRELOAD_NEXT_IMAGE_STATIC,
	"تخزين الصورة الأخيرة مؤقتًا", // LOCALIZATION_ID_CACHE_LAST_IMAGE_STATIC,
	"لون خلفية النافذة:", // LOCALIZATION_ID_WINDOWED_BACKGROUND_COLOR_STATIC,
	"لون خلفية ملء الشاشة:", // LOCALIZATION_ID_FULLSCREEN_BACKGROUND_COLOR_STATIC,
	"إجراء النقر الأيسر:", // LOCALIZATION_ID_LEFT_CLICK_ACTION_STATIC,
	"إجراء النقر الأيمن:", // LOCALIZATION_ID_RIGHT_CLICK_ACTION_STATIC,
	"إجراء عجلة الماوس:", // LOCALIZATION_ID_MOUSE_WHEEL_ACTION_STATIC,
	"الأوامر:", // LOCALIZATION_ID_COMMANDS_STATIC,
	"إعدادات الأمر المحدد", // LOCALIZATION_ID_SETTINGS_FOR_SELECTED_COMMAND,
	"إضافة...", // LOCALIZATION_ID_ADD_KEY_BUTTON,
	"تعديل...", // LOCALIZATION_ID_EDIT_KEY_BUTTON,
	"إزالة", // LOCALIZATION_ID_REMOVE_KEY_BUTTON,
	"إضافة اختصار لوحة مفاتيح", // LOCALIZATION_ID_ADD_KEYBOARD_SHORTCUT_CAPTION,
	"تعديل اختصار لوحة المفاتيح", // LOCALIZATION_ID_EDIT_KEYBOARD_SHORTCUT_CAPTION,
	"مفتاح الاختصار:", // LOCALIZATION_ID_SHORTCUT_KEY,
	"مفتاح الاختصار مستخدم حاليًا بواسطة:", // LOCALIZATION_ID_SHORTCUT_KEY_CURRENTLY_USED_BY,
	"تعيين سرعة مخصصة", // LOCALIZATION_ID_SET_CUSTOM_RATE_CAPTION,
	"السرعة المخصصة:", // LOCALIZATION_ID_CUSTOM_RATE_STATIC,
	"دقائق", // LOCALIZATION_ID_CUSTOM_RATE_MINUTES,
	"ثوانٍ", // LOCALIZATION_ID_CUSTOM_RATE_SECONDS,
	"مللي ثانية", // LOCALIZATION_ID_CUSTOM_RATE_MILLISECONDS,
	"حول void Image Viewer", // LOCALIZATION_ID_ABOUT_CAPTION,
	"إعادة تسمية", // LOCALIZATION_ID_RENAME_CAPTION,
	"الانتقال إلى", // LOCALIZATION_ID_JUMP_TO_TITLE,
	"Copyright © %d voidtools", // LOCALIZATION_ID_ABOUT_COPYRIGHT_FORMAT,
	"support@voidtools.com", // LOCALIZATION_ID_ABOUT_EMAIL,
	"www.voidtools.com", // LOCALIZATION_ID_ABOUT_WEBSITE,
	"فتح صورة", // LOCALIZATION_ID_OPEN_IMAGE_CAPTION,
	"جميع ملفات الصور", // LOCALIZATION_ID_OPEN_ALL_IMAGE_FILES,
	"جميع الملفات", // LOCALIZATION_ID_OPEN_ALL_FILES,
	"تمرير", // LOCALIZATION_ID_OPTIONS_ACTION_SCROLL_COMBOBOXITEM,
	"تشغيل/إيقاف عرض الشرائح", // LOCALIZATION_ID_OPTIONS_ACTION_PLAY_PAUSE_SLIDESHOW_COMBOBOXITEM,
	"تشغيل/إيقاف الرسوم المتحركة", // LOCALIZATION_ID_OPTIONS_ACTION_PLAY_PAUSE_ANIMATION_COMBOBOXITEM,
	"تكبير", // LOCALIZATION_ID_OPTIONS_ACTION_ZOOM_IN_COMBOBOXITEM,
	"الصورة التالية", // LOCALIZATION_ID_OPTIONS_ACTION_NEXT_IMAGE_COMBOBOXITEM,
	"تمرير 1:1", // LOCALIZATION_ID_OPTIONS_ACTION_ONE_TO_ONE_SCROLL_COMBOBOXITEM,
	"تمرير/تحريك النافذة", // LOCALIZATION_ID_OPTIONS_ACTION_SCROLL_MOVE_WINDOW_COMBOBOXITEM,
	"قائمة السياق", // LOCALIZATION_ID_OPTIONS_ACTION_CONTEXT_MENU_COMBOBOXITEM,
	"تصغير", // LOCALIZATION_ID_OPTIONS_ACTION_ZOOM_OUT_COMBOBOXITEM,
	"الصورة السابقة", // LOCALIZATION_ID_OPTIONS_ACTION_PREVIOUS_IMAGE_COMBOBOXITEM,
	"تكبير/تصغير", // LOCALIZATION_ID_OPTIONS_ACTION_ZOOM_COMBOBOXITEM,
	"التالي/السابق", // LOCALIZATION_ID_OPTIONS_ACTION_NEXT_PREV_COMBOBOXITEM,
	"السابق/التالي", // LOCALIZATION_ID_OPTIONS_ACTION_PREV_NEXT_COMBOBOXITEM,
	"تنسيق شريط العنوان:", // LOCALIZATION_ID_OPTIONS_TITLE_BAR_FORMAT_STATIC,
	"المسار الكامل", // LOCALIZATION_ID_OPTIONS_TITLE_BAR_FORMAT_FULL_PATH_COMBOBOXITEM,
	"اسم الملف فقط", // LOCALIZATION_ID_OPTIONS_TITLE_BAR_FORMAT_FILENAME_ONLY_COMBOBOXITEM,
	"لا شيء", // LOCALIZATION_ID_OPTIONS_TITLE_BAR_FORMAT_NONE_COMBOBOXITEM,
	"Everything غير متاح", // LOCALIZATION_ID_EVERYTHING_NOT_AVAILABLE_MESSAGE,
	"إضافة بحث Everything", // LOCALIZATION_ID_EVERYTHING_ADD_EVERYTHING_SEARCH_CAPTION,
	"تحميل بحث Everything", // LOCALIZATION_ID_EVERYTHING_LOAD_EVERYTHING_SEARCH_CAPTION,
	"عشوائي", // LOCALIZATION_ID_RANDOMIZE,
	"نسخ إلى", // LOCALIZATION_ID_COPY_TO_CAPTION,
	"نقل إلى", // LOCALIZATION_ID_MOVE_TO_CAPTION,

	// Association descriptions
	"صورة نقطية",
	"صورة GIF متحركة",
	"صورة HEIC",
	"صورة HEIF",
	"ملف أيقونة",
	"صورة JPEG",
	"صورة JPEG",
	"صورة PNG",
	"صورة TIFF",
	"صورة TIFF",
	"صورة WebP",
	// LOCALIZATION_ID_ABOUT_PROJECT / LOCALIZATION_ID_ABOUT_PROJECT_URL
	"صفحة المشروع",
	"https://github.com/HaiSeaman/voidImageViewer-i18n",

};
